<?xml version='1.0'?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.05" />

    <xacro:property name="base_length" value="0.7" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.1" />

    <xacro:property name="arm_link_radius" value="0.2" />
    <xacro:property name="arm_link_1_length" value="1" />
    <xacro:property name="arm_link_2_length" value="2" />
    <xacro:property name="arm_link_3_length" value="2" />

    <xacro:property name="sliding_link_1_length" value="2" />

    <xacro:include filename="$(find my_robot_simulation)/urdf/materials.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/wheel.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/arm_unit.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/sliding_unit.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/inertial.urdf.xacro" />

    <xacro:include filename="$(find my_robot_simulation)/urdf/my_robots_super_model.gazebo" />
    
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    
    <link name='base_link'>
        <visual name='base_visual'>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="grey" />
        </visual>

        <xacro:inertial_box mass="1" x="${base_length}" y="${base_width}" z="${base_height}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>

        <collision name='base_collision'>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>

        <collision name='caster_collision'>
            <origin xyz="${-0.75 * base_length / 2} 0 ${-0.5 * base_height}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${0.7 * wheel_radius}" />
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>

        <visual name='caster_visual'>
            <origin xyz="${-0.75 * base_length / 2} 0 ${-0.5 * base_height}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${0.7 * wheel_radius}" />
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <link name="sensor">
        <visual name="sensor_visual">
            <origin xyz="0 0 0.0" rpy="0.0 0.0 0"/>
            <geometry>
                <box size="0.02 0.05 0.03"/>
            </geometry>
            <material name="black"/>
        </visual>

        <xacro:inertial_box mass="0.01" x="0.02" y="0.05" z="0.03">
            <origin xyz="0 0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>

        <collision name='sensor_collision'>
            <origin xyz="0 0 0.0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.05 0.03"/>
            </geometry>
        </collision>
    </link>

    <joint name="sensor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="sensor"/>
        <origin xyz="${-base_length / 2} 0.0 0.0" rpy="0.0 0.0 ${pi}"/>
    </joint>
    

    <xacro:wheel side="left" length="${wheel_width}" radius="${wheel_radius}" link_xyz="0 ${-wheel_width / 2} 0" link_rpy="${pi / 2} 0 0" joint_xyz="${0.65 * base_length / 2} ${-base_width / 2} ${-0.5 * base_height}" joint_rpy="0 0 0" axis_xyz="0 1 0" />
    <xacro:wheel side="right" length="${wheel_width}" radius="${wheel_radius}" link_xyz='0 ${wheel_width / 2} 0' link_rpy='${pi / 2} 0 0' joint_xyz="${0.65 * base_length / 2} ${base_width / 2} ${-0.5 * base_height}" joint_rpy='0 0 0' axis_xyz='0 1 0' />

    <!-- <xacro:arm_unit number='1' parent='base_link' length="${arm_link_1_length}" radius="${arm_link_radius}" color="grey" axis='0 0 1' lower_limit='${-pi}' upper_limit='${pi}' link_xyz="0 0 ${arm_link_1_length / 2}" joint_xyz='0 0 ${base_height / 2}'/>
    <xacro:arm_unit number='2' parent='arm_unit_1' length="${arm_link_2_length}" radius="${arm_link_radius}" color="grey" axis='0 1 0' lower_limit='-1.5708' upper_limit='1.5708' link_xyz="0 0 ${arm_link_2_length / 2}" joint_xyz='0 0 ${arm_link_1_length}'/>
    <xacro:arm_unit number='3' parent='arm_unit_2' length="${arm_link_3_length}" radius="${arm_link_radius}" color="grey" axis='0 1 0' lower_limit='-1.5708' upper_limit='1.5708' link_xyz="0 0 ${arm_link_3_length / 2}" joint_xyz='0 0 ${arm_link_2_length}'/>

    <xacro:sliding_unit number='1' parent='arm_unit_3' x="${sliding_link_1_length}" y="0.4" z="0.05" color="grey" axis='1 0 0' lower_limit='${-sliding_link_1_length / 2}' upper_limit='${sliding_link_1_length / 2}' link_xyz='0 0 0.025' link_rpy='0 0 0' joint_xyz='0 0 ${arm_link_3_length}' joint_rpy='0 0 0'/> -->

    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>

</robot>