<?xml version='1.0'?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.6" />
    <xacro:property name="wheel_width" value="0.2" />

    <xacro:property name="base_length" value="5" />
    <xacro:property name="base_width" value="3" />
    <xacro:property name="base_height" value="0.3" />

    <xacro:property name="arm_link_radius" value="0.2" />
    <xacro:property name="arm_link_1_length" value="1" />
    <xacro:property name="arm_link_2_length" value="2" />
    <xacro:property name="arm_link_3_length" value="2" />

    <xacro:property name="sliding_link_1_length" value="2" />

    <xacro:include filename="$(find my_robot_simulation)/urdf/materials.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/wheel.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/arm_unit.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/sliding_unit.xacro" />
    <xacro:include filename="$(find my_robot_simulation)/urdf/inertial.urdf.xacro" />
    
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    
    <link name='base_link'>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <!-- <material name="grey" /> -->
        </visual>
        <xacro:inertial_box mass="1" x="${base_length}" y="${base_width}" z="${base_height}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
        <collision name='caster_collision'>
            <origin xyz="${-0.75 * base_length / 2} 0 ${-base_height}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${0.6 * wheel_radius}" />
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual name='caster_visual'>
            <origin xyz="${-0.75 * base_length / 2} 0 ${-base_height}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${0.6 * wheel_radius}" />
            </geometry>
            <!-- <material name="blue"/> -->
        </visual>
    </link>

    <xacro:wheel side="left" length="${wheel_width}" radius="${wheel_radius}" link_xyz="0 ${-wheel_width / 2} 0" link_rpy="${pi / 2} 0 0" joint_xyz="${0.5 * base_length / 2} ${-base_width / 2} 0" joint_rpy="0 0 0" axis_xyz="0 1 0" />
    <xacro:wheel side="right" length="${wheel_width}" radius="${wheel_radius}" link_xyz='0 ${wheel_width / 2} 0' link_rpy='${pi / 2} 0 0' joint_xyz="${0.5 * base_length / 2} ${base_width / 2} 0" joint_rpy='0 0 0' axis_xyz='0 1 0' />

    <xacro:arm_unit number='1' parent='base_link' length="${arm_link_1_length}" radius="${arm_link_radius}" color="grey" axis='0 0 1' lower_limit='${-pi}' upper_limit='${pi}' link_xyz="0 0 ${arm_link_1_length / 2}" joint_xyz='0 0 ${base_height / 2}'/>
    <xacro:arm_unit number='2' parent='arm_unit_1' length="${arm_link_2_length}" radius="${arm_link_radius}" color="grey" axis='0 1 0' lower_limit='-1.5708' upper_limit='1.5708' link_xyz="0 0 ${arm_link_2_length / 2}" joint_xyz='0 0 ${arm_link_1_length}'/>
    <xacro:arm_unit number='3' parent='arm_unit_2' length="${arm_link_3_length}" radius="${arm_link_radius}" color="grey" axis='0 1 0' lower_limit='-1.5708' upper_limit='1.5708' link_xyz="0 0 ${arm_link_3_length / 2}" joint_xyz='0 0 ${arm_link_2_length}'/>

    <xacro:sliding_unit number='1' parent='arm_unit_3' x="${sliding_link_1_length}" y="0.4" z="0.05" color="grey" axis='1 0 0' lower_limit='${-sliding_link_1_length / 2}' upper_limit='${sliding_link_1_length / 2}' link_xyz='0 0 0.025' link_rpy='0 0 0' joint_xyz='0 0 ${arm_link_3_length}' joint_rpy='0 0 0'/>

    <!-- SET COLORS FOR GAZEBO -->
    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="wheel_left">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="wheel_right">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="arm_unit_1">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="arm_unit_2">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="arm_unit_3">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="sliding_unit_1">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <legacyMode>false</legacyMode>
            <alwaysOn>true</alwaysOn>
            <updateRate>30</updateRate>
            <leftJoint>wheel_left_joint</leftJoint>
            <rightJoint>wheel_right_joint</rightJoint>
            <wheelSeparation>${base_width}</wheelSeparation>
            <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
            <wheelTorque>100</wheelTorque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo>

    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>

</robot>